### ISSUE TITLE
Legacy

### ISSUE THREAD

**Issue by kinduff** [fferegrino/techlingo.fyi-old#34]
**¿Cual es la palabra?**  
Legacy

**Si ya sabes lo que funciona, por favor cuéntanos**    
Sistema, tecnología o aplicación antiguo o desactualizado que se sigue utilizando dentro de una organización.

**Contexto**  

> No podemos agregar país a los usuarios porque esa tabla está en un sistema legacy

**Comment by fferegrino** [comment]
Gracias, cerrado con #35
